//{{NO_DEPENDENCIES}}
// Microsoft eMbedded Visual C++ generated include file.
// Used by qm.rc
//
#define IDI_MAINFRAME                   100
#define IDI_DECRYPTED                   101
#define IDI_VERIFIED                    102
#define IDI_UNVERIFIED                  103
#define IDI_OFFLINE                     104
#define IDI_ONLINE                      105
#define IDI_NEWMAIL                     106
#define IDI_MESSAGE                     107
#define IDI_EDIT                        108
#define IDI_ADDRESSBOOK                 109
#define IDB_HEADER                      200
#define IDB_ADDRESSBOOK                 201
#define IDB_SYNCNOTIFICATION            202
#define IDR_ADDRESSBOOK                 300
#define IDS_ACTION_SHOWTOOLBAR          1000
#define IDS_ACTION_HIDETOOLBAR          1001
#define IDS_ACTION_SHOWSTATUSBAR        1002
#define IDS_ACTION_HIDESTATUSBAR        1003
#define IDS_ACTION_SHOWFOLDER           1004
#define IDS_ACTION_HIDEFOLDER           1005
#define IDS_ACTION_SHOWHEADERCOLUMN     1006
#define IDS_ACTION_HIDEHEADERCOLUMN     1007
#define IDS_ACTION_SHOWPREVIEW          1008
#define IDS_ACTION_HIDEPREVIEW          1009
#define IDS_ACTION_SHOWHEADER           1010
#define IDS_ACTION_HIDEHEADER           1011
#define IDS_ACTION_SHOWTAB              1012
#define IDS_ACTION_HIDETAB              1013
#define IDS_ACTION_SHOWMAIN             1014
#define IDS_ACTION_HIDEMAIN             1015
#define IDS_ACTION_DIALUPCONNECT        1016
#define IDS_ACTION_DIALUPDISCONNECT     1017
#define IDS_ACTION_SUBSCRIBE            1018
#define IDS_MENU_THISFOLDER             1100
#define IDS_MENU_NONE                   1101
#define IDS_MENU_GOROUND                1102
#define IDS_PROGRESS_APPLYRULES         1200
#define IDS_PROGRESS_CHECK              1201
#define IDS_PROGRESS_COMPACT            1202
#define IDS_PROGRESS_COPYMESSAGE        1203
#define IDS_PROGRESS_DELETE             1204
#define IDS_PROGRESS_DUMP               1205
#define IDS_PROGRESS_EMPTYTRASH         1206
#define IDS_PROGRESS_EXPORT             1207
#define IDS_PROGRESS_IMPORT             1208
#define IDS_PROGRESS_LOAD               1209
#define IDS_PROGRESS_MOVEMESSAGE        1210
#define IDS_PROGRESS_PROCESS            1211
#define IDS_PROGRESS_SALVAGE            1212
#define IDS_ADDRESSBOOK_ALLCATEGORY     1300
#define IDS_ADDRESSBOOK_THISCATEGORY    1301
#define IDS_ADDRESSBOOK_CATEGORY        1302
#define IDS_ADDRESSBOOK_CATEGORYALL     1303
#define IDS_ADDRESSBOOK_COLUMN_NAME     1310
#define IDS_ADDRESSBOOK_COLUMN_ADDRESS  1311
#define IDS_ADDRESSBOOK_COLUMN_COMMENT  1312
#define IDS_TITLE_ACCOUNT               1400
#define IDS_TITLE_ADDRESSBOOK           1401
#define IDS_TITLE_COLORS                1402
#define IDS_TITLE_COLORSETS             1403
#define IDS_TITLE_FULLTEXTSEARCH        1404
#define IDS_TITLE_MACROSEARCH           1405
#define IDS_TITLE_PROPERTY              1406
#define IDS_TITLE_RULES                 1407
#define IDS_TITLE_RULESETS              1408
#define IDS_TITLE_SEARCH                1409
#define IDS_TITLE_TEMPORARYFOLDER       1410
#define IDS_FOLDERLIST_NAME             1500
#define IDS_FOLDERLIST_ID               1501
#define IDS_FOLDERLIST_COUNT            1502
#define IDS_FOLDERLIST_UNSEENCOUNT      1503
#define IDS_FOLDERLIST_SIZE             1504
#define IDS_STATUS_VIEWMODELTEMPLATE    1600
#define IDS_STATUS_VIEWMODELTEMPLATESHORT 1601
#define IDS_STATUS_ONLINE               1602
#define IDS_STATUS_OFFLINE              1603
#define IDS_STATUS_CUSTOM               1604
#define IDS_STATUS_NONE                 1605
#define IDS_ARGUMENT_NAME               1700
#define IDS_ARGUMENT_VALUE              1701
#define IDS_FILTER_EXPORT               1800
#define IDS_FILTER_IMPORT               1801
#define IDS_FILTER_INSERT               1802
#define IDS_FILTER_OPEN                 1803
#define IDS_FILTER_SAVE                 1804
#define IDS_FILTER_ATTACHMENT           1805
#define IDS_FILTER_SOUND                1806
#define IDS_FILTER_EXECUTABLE           1807
#define IDS_COLUMN_TITLE                1900
#define IDS_COLUMN_TYPE                 1901
#define IDS_COLUMN_WIDTH                1902
#define IDS_COLUMNTYPE_ID               2000
#define IDS_COLUMNTYPE_DATE             2001
#define IDS_COLUMNTYPE_FROM             2002
#define IDS_COLUMNTYPE_TO               2003
#define IDS_COLUMNTYPE_FROMTO           2004
#define IDS_COLUMNTYPE_SUBJECT          2005
#define IDS_COLUMNTYPE_SIZE             2006
#define IDS_COLUMNTYPE_FLAGS            2007
#define IDS_COLUMNTYPE_LABEL            2008
#define IDS_COLUMNTYPE_OTHER            2009
#define IDS_RULE_NONE                   2100
#define IDS_RULE_MOVE                   2101
#define IDS_RULE_COPY                   2102
#define IDS_RULE_DELETE                 2103
#define IDS_RULE_LABEL                  2104
#define IDS_RULE_DELETECACHE            2105
#define IDS_RULE_APPLY                  2106
#define IDS_LABEL_SET                   2200
#define IDS_LABEL_ADD                   2201
#define IDS_LABEL_REMOVE                2202
#define IDS_PROPERTY_NAME               2300
#define IDS_PROPERTY_VALUE              2301
#define IDS_PANEL_ADDRESSBOOK           2400
#define IDS_PANEL_AUTOPILOT             2401
#define IDS_PANEL_COLORS                2402
#define IDS_PANEL_CONFIRM               2403
#define IDS_PANEL_EDIT                  2404
#define IDS_PANEL_EDIT2                 2405
#define IDS_PANEL_FILTERS               2406
#define IDS_PANEL_FIXEDFORMTEXTS        2407
#define IDS_PANEL_FOLDER                2408
#define IDS_PANEL_GOROUND               2409
#define IDS_PANEL_HEADER                2410
#define IDS_PANEL_JUNK                  2411
#define IDS_PANEL_LIST                  2412
#define IDS_PANEL_MESSAGE               2413
#define IDS_PANEL_MISC                  2414
#define IDS_PANEL_MISC2                 2415
#define IDS_PANEL_PREVIEW               2416
#define IDS_PANEL_RULES                 2417
#define IDS_PANEL_SEARCH                2418
#define IDS_PANEL_SECURITY              2419
#define IDS_PANEL_SIGNATURES            2420
#define IDS_PANEL_SYNC                  2421
#define IDS_PANEL_SYNCFILTERS           2422
#define IDS_PANEL_TAB                   2423
#define IDS_SIGNATURE_NONE              2500
#define IDS_SYNCFILTERACTION_DOWNLOADPOP3 2600
#define IDS_SYNCFILTERACTION_DOWNLOADIMAP4 2601
#define IDS_SYNCFILTERACTION_DOWNLOADNNTP 2602
#define IDS_SYNCFILTERACTION_DELETE     2603
#define IDS_SYNCFILTERACTION_IGNORE     2604
#define IDS_SYNCFILTERIMAP4DOWNLOADTYPE_ALL 2700
#define IDS_SYNCFILTERIMAP4DOWNLOADTYPE_TEXT 2701
#define IDS_SYNCFILTERIMAP4DOWNLOADTYPE_HTML 2702
#define IDS_SYNCFILTERIMAP4DOWNLOADTYPE_HEADER 2703
#define IDS_SYNC_ALWAYS                 2800
#define IDS_SYNC_NEVER                  2801
#define IDS_SYNC_AUTO                   2802
#define IDS_SYNC_MANUAL                 2803
#define IDS_DEFAULTSUBACCOUNT           3000
#define IDS_LOCALFOLDER                 3001
#define IDS_SYNCABLELOCALFOLDER         3002
#define IDS_REMOTEFOLDER                3003
#define IDS_QUERYFOLDER                 3004
#define IDS_OSDEFAULT                   3005
#define IDS_ALLFOLDER                   3006
#define IDS_UNSPECIFIED                 3007
#define IDS_RESOURCEPATH                3008
#define IDS_INVOKEACTION                3009
#define IDS_ACTION                      3010
#define IDS_EXECUTEMACRO                3011
#define IDS_MACRO                       3012
#define IDS_OFFLINE                     3013
#define IDS_JUNKREPAIRED                3014
#define IDS_MESSAGE_UPDATEFOLDER        5000
#define IDS_MESSAGE_FINISHED            5001
#define IDS_MESSAGE_CHECKMESSAGES       5002
#define IDS_MESSAGE_APPLYRULE           5003
#define IDS_MESSAGE_FINDNOTFOUND        5004
#define IDS_MESSAGE_UPDATED             5005
#define IDS_CONFIRM_OVERWRITE           6000
#define IDS_CONFIRM_EXECUTEATTACHMENT   6001
#define IDS_CONFIRM_DELETETEMPFILE      6002
#define IDS_CONFIRM_IGNORELOCK          6003
#define IDS_CONFIRM_REMOVEACCOUNT       6004
#define IDS_CONFIRM_REMOVESUBACCOUNT    6005
#define IDS_CONFIRM_REMOVEFOLDER        6006
#define IDS_CONFIRM_EMPTYFOLDER         6007
#define IDS_CONFIRM_EMPTYTRASH          6008
#define IDS_CONFIRM_DELETEMESSAGE       6009
#define IDS_CONFIRM_SAVEADDRESSBOOK     6010
#define IDS_CONFIRM_EXIT                6011
#define IDS_CONFIRM_OPENURL             6012
#define IDS_CONFIRM_IGNORECHECKERROR    6013
#define IDS_CONFIRM_UPDATE              6014
#define IDS_ERROR_CREATEFOLDER          10000
#define IDS_ERROR_EXECUTEATTACHMENT     10001
#define IDS_ERROR_DIALUP                10002
#define IDS_ERROR_CLEARDELETED          10003
#define IDS_ERROR_COPYMESSAGES          10004
#define IDS_ERROR_CUTMESSAGES           10005
#define IDS_ERROR_DELETECACHE           10006
#define IDS_ERROR_DELETEMESSAGES        10007
#define IDS_ERROR_PASTEMESSAGES         10008
#define IDS_ERROR_COMPACT               10009
#define IDS_ERROR_SAVE                  10010
#define IDS_ERROR_EXPORT                10011
#define IDS_ERROR_IMPORT                10012
#define IDS_ERROR_PRINT                 10013
#define IDS_ERROR_SALVAGE               10014
#define IDS_ERROR_DELETEFOLDER          10015
#define IDS_ERROR_EMPTYFOLDER           10016
#define IDS_ERROR_EMPTYTRASH            10017
#define IDS_ERROR_RENAMEFOLDER          10018
#define IDS_ERROR_UPDATEFOLDER          10019
#define IDS_ERROR_APPLYRULE             10020
#define IDS_ERROR_APPLYTEMPLATE         10021
#define IDS_ERROR_COMBINE               10022
#define IDS_ERROR_CREATEMESSAGE         10023
#define IDS_ERROR_DELETEATTACHMENT      10024
#define IDS_ERROR_DETACHATTACHMENT      10025
#define IDS_ERROR_EXPANDDIGEST          10026
#define IDS_ERROR_MARKMESSAGE           10027
#define IDS_ERROR_MOVEMESSAGE           10028
#define IDS_ERROR_COPYMESSAGE           10029
#define IDS_ERROR_OPENURL               10030
#define IDS_ERROR_SETFLAGS              10031
#define IDS_ERROR_SEARCH                10032
#define IDS_ERROR_DIALUPCONNECT         10033
#define IDS_ERROR_DIALUPDISCONNECT      10034
#define IDS_ERROR_GOROUND               10035
#define IDS_ERROR_SYNC                  10036
#define IDS_ERROR_OPENLINK              10037
#define IDS_ERROR_REFRESH               10038
#define IDS_ERROR_INSERTFILE            10039
#define IDS_ERROR_PASTE                 10040
#define IDS_ERROR_OPENFILE              10041
#define IDS_ERROR_SAVEFILE              10042
#define IDS_ERROR_SEND                  10043
#define IDS_ERROR_DUMP                  10044
#define IDS_ERROR_LOAD                  10045
#define IDS_ERROR_CHECK                 10046
#define IDS_ERROR_INVALIDMACRO          10047
#define IDS_ERROR_CREATEACCOUNT         10048
#define IDS_ERROR_MOVEFOLDER            10049
#define IDS_ERROR_SAVEADDRESSBOOK       10050
#define IDS_ERROR_UNDO                  10051
#define IDS_ERROR_COMPLEXMACRO          10052
#define IDS_ERROR_NOOUTBOX              10053
#define IDS_ERROR_LOADOUTBOX            10054
#define IDS_ERROR_NOSENTBOX             10055
#define IDS_ERROR_GETMESSAGE            10056
#define IDS_ERROR_MOVETOSENTBOX         10057
#define IDS_ERROR_LABELMESSAGE          10058
#define IDS_ERROR_SYNCHRONIZING         10059
#define IDS_ERROR_EVALUATEMACRO         10060
#define IDS_ERROR_RENAMEACCOUNT         10061
#define IDS_ERROR_RENAMESUBACCOUNT      10062
#define IDS_ERROR_CREATESUBACCOUNT      10063
#define IDS_ERROR_OUTBOXHASEXTRAFLAGS   10064
#define IDS_ERROR_OPENMESSAGE           10065
#define IDS_ERROR_CHECKUPDATE           10066
#define IDS_ERROR_REPAIRJUNK            10067
#define IDS_ERROR_INVALIDACCOUNT        10068
#define IDS_ERROR_INVALIDFOLDER         10069
#define IDS_ERROR_INVALIDCOLOR          10070
#define IDS_ERROR_INSERTSIGNATURE       10071
#define IDS_ERROR_INSERTTEXT            10072
#define IDS_ERROR_REFORM                10073

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
