//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by qmppc.rc
//
#define IDI_MAINFRAME                   102
#define IDB_FOLDER                      104
#define IDB_HEADER                      105
#define IDB_LIST                        106
#define IDB_LISTDATA                    107
#define IDD_SYNC                        110
#define IDD_SELECTSYNCFILTER            111
#define IDD_CREATEFOLDER                112
#define IDD_PROGRESS                    113
#define IDD_DETACH                      114
#define IDD_ADDRESSBOOK                 115
#define IDD_ATTACHMENT                  117
#define IDB_ADDRESSBOOK                 118
#define IDD_MESSAGEPROPERTY             119
#define IDD_EXPORT                      120
#define IDD_IMPORT                      121
#define IDR_VIEWSORT                    123
#define IDR_MESSAGEMOVE                 124
#define IDR_VIEWFILTER                  125
#define IDR_VIEWTEMPLATE                126
#define IDR_VIEWENCODING                127
#define IDR_MESSAGEAPPLYTEMPLATE        128
#define IDR_MESSAGEAPPLYTEMPLATEEXTERNAL 129
#define IDR_MESSAGEATTACHMENT           130
#define IDR_TOOLSUBACCOUNT              131
#define IDD_ACCOUNT                     132
#define IDD_ACCOUNTGENERAL              133
#define IDD_ACCOUNTUSER                 134
#define IDD_ACCOUNTDIALUP               135
#define IDD_ACCOUNTADVANCED             136
#define IDR_TOOLGOROUND                 137
#define IDR_TOOLSCRIPT                  138
#define IDD_CREATEACCOUNT               139
#define IDD_MAILFOLDER                  140
#define IDD_FIND                        141
#define IDD_REPLACE                     142
#define IDD_CREATESUBACCOUNT            143
#define IDD_DIALUP                      144
#define IDD_SELECTDIALUPENTRY           145
#define IDD_FOLDERPROPERTY              146
#define IDD_SINGLEINPUTBOX              147
#define IDD_MULTIINPUTBOX               148
#define IDB_SYNCNOTIFICATION            149
#define IDD_CUSTOMFILTER                150
#define IDB_ACCOUNT                     150
#define IDD_MOVEMESSAGE                 151
#define IDD_RENAME                      152
#define IDD_MACROSEARCH                 153
#define IDD_FOLDERCONDITION             155
#define IDD_VIEWS                       157
#define IDD_VIEWSCOLUMN                 158
#define IDD_FOLDERPARAMETER             159
#define IDD_PARAMETER                   160
#define IDD_GOROUND                     161
#define IDD_GOROUNDCOURSE               162
#define IDD_GOROUNDENTRY                163
#define IDD_GOROUNDDIALUP               164
#define IDD_ACCOUNTDETAIL               165
#define IDD_RESOURCE                    166
#define IDD_SIGNATURES                  167
#define IDD_SIGNATURE                   168
#define IDR_TOOLINSERTTEXT              169
#define IDD_FIXEDFORMTEXTS              170
#define IDD_FIXEDFORMTEXT               171
#define IDD_PASSWORD                    172
#define IDD_RULECOLORSETS               173
#define IDD_RULESCOLORS                 174
#define IDD_RULE                        175
#define IDD_COLOR                       176
#define IDD_COPYRULETEMPLATE            177
#define IDD_ARGUMENT                    178
#define IDD_CONDITION                   179
#define IDR_ADDRESSBOOK                 180
#define IDC_SYNCSTATUS                  1000
#define IDS_SHOWTOOLBAR                 1001
#define IDC_FILTERSETLIST               1001
#define IDS_HIDETOOLBAR                 1002
#define IDS_SHOWSTATUSBAR               1003
#define IDC_SIZEGRIP                    1003
#define IDS_HIDESTATUSBAR               1004
#define IDS_SHOWFOLDER                  1005
#define IDC_LOCALFOLDER                 1005
#define IDS_HIDEFOLDER                  1006
#define IDC_REMOTEFOLDER                1006
#define IDS_SHOWHEADERCOLUMN            1007
#define IDC_QUERYFOLDER                 1007
#define IDS_HIDEHEADERCOLUMN            1008
#define IDC_NAME                        1008
#define IDS_SHOWPREVIEW                 1009
#define IDC_MACRO                       1009
#define IDS_HIDEPREVIEW                 1010
#define IDC_MESSAGE                     1010
#define IDS_SHOWHEADER                  1011
#define IDC_PROGRESS                    1011
#define IDS_HIDEHEADER                  1012
#define IDC_ATTACHMENT                  1012
#define IDS_THISFOLDER                  1013
#define IDC_FOLDER                      1013
#define IDS_NONE                        1014
#define IDC_BROWSE                      1014
#define IDS_GOROUND                     1015
#define IDC_RENAME                      1015
#define IDS_CANCEL                      1016
#define IDC_LIST                        1016
#define IDS_APPLYMESSAGERULES           1017
#define IDC_ADDRESS                     1017
#define IDS_CONFIRMOVERWRITE            1018
#define IDC_SELECTEDADDRESS             1018
#define IDS_CONFIRMEXECUTEATTACHMENT    1019
#define IDC_TO                          1019
#define IDS_CONFIRMDELETETEMPFILE       1020
#define IDC_CC                          1020
#define IDC_BCC                         1021
#define IDS_PROPERTY                    1021
#define IDC_REMOVE                      1022
#define IDS_ALLCATEGORY                 1022
#define IDC_CATEGORY                    1023
#define IDS_CATEGORY                    1023
#define IDS_CATEGORYALL                 1024
#define IDC_ADD                         1025
#define IDS_DEFAULTSUBACCOUNT           1025
#define IDS_ACCOUNT                     1026
#define IDC_DATE                        1027
#define IDS_TEMPLATENONE                1027
#define IDC_SUBJECT                     1028
#define IDS_SCRIPTNONE                  1028
#define IDC_ID                          1029
#define IDS_FOLDERLISTNAME              1029
#define IDC_MESSAGESIZE                 1030
#define IDS_FOLDERLISTID                1030
#define IDC_SEEN                        1031
#define IDS_FOLDERLISTCOUNT             1031
#define IDC_REPLIED                     1032
#define IDS_FOLDERLISTUNSEENCOUNT       1032
#define IDC_FORWARDED                   1033
#define IDS_FOLDERLISTSIZE              1033
#define IDC_DELETED                     1034
#define IDC_SENT                        1035
#define IDS_FINDNOTFOUND                1035
#define IDC_DRAFT                       1036
#define IDS_CONFIRMCLOSEEDITFRAME       1036
#define IDC_MARKED                      1037
#define IDS_DIALUPCONNECT               1037
#define IDC_DOWNLOAD                    1038
#define IDS_DIALUPDISCONNECT            1038
#define IDC_DOWNLOADTEXT                1039
#define IDS_NORMALFOLDER                1039
#define IDC_TOME                        1040
#define IDS_QUERYFOLDER                 1040
#define IDC_CCME                        1041
#define IDS_LOCALFOLDER                 1041
#define IDC_USER1                       1042
#define IDS_REMOTEFOLDER                1042
#define IDC_USER2                       1043
#define IDS_FOLDERTYPETEMPLATE          1043
#define IDC_USER3                       1044
#define IDS_EXPORT                      1044
#define IDC_USER4                       1045
#define IDS_IMPORT                      1045
#define IDC_FROM                        1046
#define IDS_CONFIRMIGNORELOCK           1046
#define IDC_PATH                        1047
#define IDS_MOVEMESSAGE                 1047
#define IDS_COPYMESSAGE                 1048
#define IDS_EMPTYTRASH                  1049
#define IDS_DELETE                      1050
#define IDC_ENCODING                    1051
#define IDS_CUSTOM                      1051
#define IDC_TEMPLATE                    1052
#define IDS_VIEWMODELSTATUSTEMPLATE     1052
#define IDC_FILEPERMESSAGE              1053
#define IDS_ONLINE                      1053
#define IDS_OFFLINE                     1054
#define IDS_CONFIRMREMOVEACCOUNT        1055
#define IDS_CONFIRMREMOVESUBACCOUNT     1056
#define IDS_CONFIRMREMOVEFOLDER         1057
#define IDC_EXPORTFLAGS                 1058
#define IDS_THISCATEGORY                1058
#define IDC_NORMAL                      1059
#define IDS_SEARCH                      1059
#define IDC_QMAIL20COMPATIBLE           1060
#define IDS_MACROSEARCH                 1060
#define IDC_IGNORE                      1061
#define IDC_MULTIMESSAGES               1062
#define IDS_ALLFOLDER                   1062
#define IDC_ACCOUNT                     1063
#define IDS_SYNCHRONIZING               1063
#define IDC_ADDACCOUNT                  1064
#define IDS_COMPACT                     1064
#define IDC_ADDSUBACCOUNT               1065
#define IDS_SALVAGE                     1065
#define IDS_DUMP                        1066
#define IDS_LOAD                        1067
#define IDC_PROPERTY                    1068
#define IDS_CHECK                       1068
#define IDC_RECEIVEHOST                 1069
#define IDS_IGNORECHECKERROR            1069
#define IDC_SENDHOST                    1070
#define IDC_SENDAUTHENTICATE            1070
#define IDS_TITLE                       1070
#define IDC_RECEIVEUSERNAME             1071
#define IDS_TYPE                        1071
#define IDC_RECEIVEPASSWORD             1072
#define IDC_IDENTITY                    1072
#define IDS_WIDTH                       1072
#define IDC_SENDUSERNAME                1073
#define IDC_MYADDRESS                   1073
#define IDS_CLEARRECENTS                1073
#define IDC_SENDPASSWORD                1074
#define IDC_TIMEOUT                     1074
#define IDS_UNSPECIFIED                 1074
#define IDC_CONNECTRECEIVEHOSTBEFORESEND 1075
#define IDC_INCOMINGPROTOCOL            1077
#define IDS_RESOURCEPATH                1077
#define IDC_OUTGOINGPROTOCOL            1078
#define IDS_RULESETS                    1078
#define IDC_SINGLEFILE                  1079
#define IDS_RULES                       1079
#define IDC_MULTIPLEFILE                1080
#define IDS_COLORSETS                   1080
#define IDC_BLOCKSIZE                   1081
#define IDS_COLORS                      1081
#define IDC_INDEXBLOCKSIZE              1082
#define IDS_NAME                        1082
#define IDC_MAILFOLDER                  1083
#define IDS_VALUE                       1083
#define IDS_CONFIRMEMPTYFOLDER          1084
#define IDC_ERROR                       1085
#define IDS_CONFIRMEMPTYTRASH           1085
#define IDS_CONFIRMDELETEMESSAGE        1086
#define IDC_MATCHCASE                   1087
#define IDC_FINDNEXT                    1088
#define IDC_FINDPREV                    1089
#define IDC_FIND                        1090
#define IDC_REPLACE                     1091
#define IDC_REPLACENEXT                 1092
#define IDC_REPLACEPREV                 1093
#define IDC_REPLACEALL                  1094
#define IDC_NEVER                       1095
#define IDC_WHENEVERNOTCONNECTED        1096
#define IDC_CONNECT                     1097
#define IDC_ENTRY                       1098
#define IDC_SHOWDIALOG                  1099
#define IDS_FILTER_EXPORT               1100
#define IDC_DIALPROPERTY                1100
#define IDS_FILTER_IMPORT               1101
#define IDC_WAITBEFOREDISCONNECT        1101
#define IDS_FILTER_INSERT               1102
#define IDC_SYNCFILTER                  1102
#define IDC_CANCEL                      1103
#define IDS_FILTER_OPEN                 1103
#define IDS_FILTER_SAVE                 1104
#define IDC_USERNAME                    1104
#define IDS_FILTER_ATTACHMENT           1105
#define IDC_PASSWORD                    1105
#define IDC_DOMAIN                      1106
#define IDC_DIALFROM                    1107
#define IDC_TYPE                        1108
#define IDC_SYNCWHENOPEN                1109
#define IDC_CACHEWHENREAD               1110
#define IDC_INBOX                       1111
#define IDC_OUTBOX                      1112
#define IDC_SENTBOX                     1113
#define IDC_DRAFTBOX                    1114
#define IDC_TRASHBOX                    1115
#define IDC_VALUE                       1116
#define IDC_HIDE                        1117
#define IDC_TREATASSENT                 1118
#define IDC_CLASS                       1119
#define IDC_COPY                        1122
#define IDC_ADDMESSAGEID                1123
#define IDC_SHOWHIDDEN                  1125
#define IDC_IGNOREUNSEEN                1126
#define IDC_CONDITION                   1127
#define IDC_CURRENT                     1128
#define IDC_RECURSIVE                   1129
#define IDC_ALLFOLDER                   1130
#define IDC_SEARCHBODY                  1131
#define IDC_DRIVER                      1133
#define IDC_FILTER                      1134
#define IDC_FILTERLABEL                 1135
#define IDC_REGEX                       1136
#define IDC_COLUMNS                     1138
#define IDC_EDIT                        1141
#define IDC_UP                          1142
#define IDC_DOWN                        1143
#define IDC_TITLE                       1144
#define IDC_INDENT                      1147
#define IDC_LINE                        1148
#define IDC_ASICON                      1150
#define IDC_LEFTALIGN                   1151
#define IDC_RIGHTALIGN                  1152
#define IDC_SORTTEXT                    1153
#define IDC_SORTNUMBER                  1154
#define IDC_SORTDATE                    1155
#define IDC_WIDTH                       1156
#define IDC_ASDEFAULT                   1157
#define IDC_APPLYDEFAULT                1158
#define IDC_INHERIT                     1159
#define IDC_APPLYTOALL                  1160
#define IDC_APPLYTOCHILDREN             1161
#define IDC_PARAMETER                   1163
#define IDC_SYNCABLE                    1166
#define IDC_COURSE                      1167
#define IDC_CONFIRM                     1172
#define IDC_SEQUENTIAL                  1173
#define IDC_PARALLEL                    1174
#define IDC_DIALUP                      1184
#define IDC_SUBACCOUNT                  1186
#define IDC_SENDRECEIVE                 1187
#define IDC_RECEIVE                     1188
#define IDC_SEND                        1189
#define IDC_SELECTFOLDER                1191
#define IDC_CONNECTRECEIVEBEFORESEND    1193
#define IDS_COLUMNTYPE_ID               1200
#define IDS_COLUMNTYPE_DATE             1201
#define IDC_RECEIVEPORT                 1201
#define IDS_COLUMNTYPE_FROM             1202
#define IDC_SENDPORT                    1202
#define IDS_COLUMNTYPE_TO               1203
#define IDS_COLUMNTYPE_FROMTO           1204
#define IDC_RECEIVENOSECURE             1204
#define IDS_COLUMNTYPE_SUBJECT          1205
#define IDC_RECEIVESSL                  1205
#define IDS_COLUMNTYPE_SIZE             1206
#define IDC_RECEIVESTARTTLS             1206
#define IDS_COLUMNTYPE_FLAGS            1207
#define IDC_SENDNOSECURE                1207
#define IDS_COLUMNTYPE_OTHER            1208
#define IDC_SENDSSL                     1208
#define IDC_SENDSTARTTLS                1209
#define IDC_RECEIVELOG                  1210
#define IDC_SENDLOG                     1211
#define IDC_RESOURCE                    1212
#define IDC_BACKUP                      1213
#define IDC_CHECKALL                    1214
#define IDC_CLEARALL                    1215
#define IDC_SIGNATURES                  1216
#define IDC_DEFAULT                     1217
#define IDC_SIGNATURE                   1218
#define IDC_TEXTS                       1219
#define IDC_TEXT                        1220
#define IDC_DONTSAVE                    1221
#define IDC_SESSION                     1222
#define IDC_SAVE                        1223
#define IDC_HINT                        1224
#define IDC_CACHE                       1225
#define IDC_RULECOLORSETS               1226
#define IDC_RULESCOLORS                 1232
#define IDC_MOVE                        1241
#define IDC_DELETE                      1245
#define IDC_APPLY                       1246
#define IDC_DIRECT                      1247
#define IDC_ACTION                      1250
#define IDC_ACCOUNTLABEL                1251
#define IDC_FOLDERLABEL                 1252
#define IDC_MACROLABEL                  1253
#define IDC_COLOR                       1254
#define IDC_CHOOSE                      1255
#define IDC_ARGUMENT                    1263
#define IDS_SYNCMSG_FINISHED            2001
#define IDS_SYNCMSG_SENDMESSAGES        2002
#define IDS_APPLYRULE_CHECKINGMESSAGES  2101
#define IDS_APPLYRULE_APPLYINGRULE      2102
#define IDS_ADDRESSBOOK_NAME            2201
#define IDS_ADDRESSBOOK_ADDRESS         2202
#define IDS_ADDRESSBOOK_COMMENT         2203
#define IDS_PROPERTY_NAME               2301
#define IDS_PROPERTY_VALUE              2302
#define IDS_ERROR_CREATEFOLDER          10000
#define IDS_ERROR_EXECUTEATTACHMENT     10001
#define IDS_ERROR_DIALUP                10002
#define IDS_ERROR_CLEARDELETED          10003
#define IDS_ERROR_COPYMESSAGES          10004
#define IDS_ERROR_CUTMESSAGES           10005
#define IDS_ERROR_DELETECACHE           10006
#define IDS_ERROR_DELETEMESSAGES        10007
#define IDS_ERROR_PASTEMESSAGES         10008
#define IDS_ERROR_COMPACT               10009
#define IDS_ERROR_SAVE                  10010
#define IDS_ERROR_EXPORT                10011
#define IDS_ERROR_IMPORT                10012
#define IDS_ERROR_PRINT                 10013
#define IDS_ERROR_SALVAGE               10014
#define IDS_ERROR_DELETEFOLDER          10015
#define IDS_ERROR_EMPTYFOLDER           10016
#define IDS_ERROR_EMPTYTRASH            10017
#define IDS_ERROR_RENAMEFOLDER          10018
#define IDS_ERROR_UPDATEFOLDER          10019
#define IDS_ERROR_APPLYRULE             10020
#define IDS_ERROR_APPLYTEMPLATE         10021
#define IDS_ERROR_COMBINE               10022
#define IDS_ERROR_CREATEMESSAGE         10023
#define IDS_ERROR_DELETEATTACHMENT      10024
#define IDS_ERROR_DETACHATTACHMENT      10025
#define IDS_ERROR_EXPANDDIGEST          10026
#define IDS_ERROR_MARKMESSAGE           10027
#define IDS_ERROR_MOVEMESSAGE           10028
#define IDS_ERROR_COPYMESSAGE           10029
#define IDS_ERROR_OPENURL               10030
#define IDS_ERROR_SETFLAGS              10031
#define IDS_ERROR_SEARCH                10032
#define IDS_ERROR_DIALUPCONNECT         10033
#define IDS_ERROR_DIALUPDISCONNECT      10034
#define IDS_ERROR_GOROUND               10035
#define IDS_ERROR_SYNC                  10036
#define IDS_ERROR_OPENLINK              10037
#define IDS_ERROR_REFRESH               10038
#define IDS_ERROR_INSERTFILE            10039
#define IDS_ERROR_PASTE                 10040
#define IDS_ERROR_OPENFILE              10041
#define IDS_ERROR_SAVEFILE              10042
#define IDS_ERROR_SEND                  10043
#define IDS_ERROR_DUMP                  10044
#define IDS_ERROR_LOAD                  10045
#define IDS_ERROR_CHECK                 10046
#define IDS_ERROR_INVALIDMACRO          10047
#define IDS_ERROR_CREATEACCOUNT         10048
#define IDS_ERROR_MOVEFOLDER            10049
#define IDM_EDIT_CLEARDELETED           40001
#define IDM_EDIT_COPY                   40002
#define IDM_EDIT_CUT                    40003
#define IDM_EDIT_DELETE                 40004
#define IDM_EDIT_DELETEBACKWARDCHAR     40005
#define IDM_EDIT_DELETEBACKWARDWORD     40006
#define IDM_EDIT_DELETECACHE            40007
#define IDM_EDIT_DELETECHAR             40008
#define IDM_EDIT_DELETEDIRECT           40009
#define IDM_EDIT_DELETEWORD             40010
#define IDM_EDIT_FIND                   40011
#define IDM_EDIT_FINDNEXT               40012
#define IDM_EDIT_FINDPREV               40013
#define IDM_EDIT_MOVECHARLEFT           40014
#define IDM_EDIT_MOVECHARRIGHT          40015
#define IDM_EDIT_MOVELINEDOWN           40016
#define IDM_EDIT_MOVELINEEND            40017
#define IDM_EDIT_MOVELINESTART          40018
#define IDM_EDIT_MOVELINEUP             40019
#define IDM_EDIT_MOVEPAGEDOWN           40020
#define IDM_EDIT_MOVEPAGEUP             40021
#define IDM_EDIT_MOVEDOCEND             40022
#define IDM_EDIT_MOVEDOCSTART           40023
#define IDM_EDIT_PASTE                  40024
#define IDM_EDIT_PASTEWITHQUOTE         40025
#define IDM_EDIT_REDO                   40026
#define IDM_EDIT_REPLACE                40027
#define IDM_EDIT_SELECTALL              40028
#define IDM_EDIT_UNDO                   40029
#define IDM_FILE_CHECK                  41001
#define IDM_FILE_CLOSE                  41002
#define IDM_FILE_COMPACT                41003
#define IDM_FILE_DRAFT                  41004
#define IDM_FILE_DRAFTCLOSE             41005
#define IDM_FILE_DUMP                   41006
#define IDM_FILE_EXIT                   41007
#define IDM_FILE_EXPORT                 41008
#define IDM_FILE_IMPORT                 41009
#define IDM_FILE_INSERT                 41010
#define IDM_FILE_LOAD                   41011
#define IDM_FILE_OFFLINE                41012
#define IDM_FILE_OPEN                   41013
#define IDM_FILE_PRINT                  41014
#define IDM_FILE_SALVAGE                41015
#define IDM_FILE_SAVE                   41016
#define IDM_FILE_SEND                   41017
#define IDM_FILE_SENDNOW                41018
#define IDM_FOLDER_COLLAPSE             42001
#define IDM_FOLDER_CREATE               42002
#define IDM_FOLDER_DELETE               42003
#define IDM_FOLDER_EMPTY                42004
#define IDM_FOLDER_EMPTYTRASH           42005
#define IDM_FOLDER_EXPAND               42006
#define IDM_FOLDER_PROPERTY             42007
#define IDM_FOLDER_RENAME               42008
#define IDM_FOLDER_SHOWSIZE             42009
#define IDM_FOLDER_UPDATE               42010
#define IDM_MESSAGE_APPLYRULE           43001
#define IDM_MESSAGE_APPLYRULEALL        43002
#define IDM_MESSAGE_APPLYRULESELECTED   43003
#define IDM_MESSAGE_APPLYTEMPLATENONE   43004
#define IDM_MESSAGE_APPLYTEMPLATENONEEXTERNAL 43005
#define IDM_MESSAGE_CLEARRECENTS        43006
#define IDM_MESSAGE_COMBINE             43007
#define IDM_MESSAGE_CREATEFROMCLIPBOARD 43008
#define IDM_MESSAGE_CREATEFROMFILE      43009
#define IDM_MESSAGE_DELETEATTACHMENT    43010
#define IDM_MESSAGE_DETACH              43011
#define IDM_MESSAGE_DRAFTFROMCLIPBOARD  43012
#define IDM_MESSAGE_DRAFTFROMFILE       43013
#define IDM_MESSAGE_EDIT                43014
#define IDM_MESSAGE_EDITEXTERNAL        43015
#define IDM_MESSAGE_EXPANDDIGEST        43016
#define IDM_MESSAGE_FORWARD             43017
#define IDM_MESSAGE_FORWARDEXTERNAL     43018
#define IDM_MESSAGE_MARK                43019
#define IDM_MESSAGE_MARKDELETED         43020
#define IDM_MESSAGE_MARKDOWNLOAD        43021
#define IDM_MESSAGE_MARKDOWNLOADTEXT    43022
#define IDM_MESSAGE_MARKSEEN            43023
#define IDM_MESSAGE_MOVEOTHER           43024
#define IDM_MESSAGE_NEW                 43025
#define IDM_MESSAGE_NEWEXTERNAL         43026
#define IDM_MESSAGE_OPENLINK            43027
#define IDM_MESSAGE_OPENURL             43028
#define IDM_MESSAGE_PROPERTY            43029
#define IDM_MESSAGE_REPLY               43030
#define IDM_MESSAGE_REPLYEXTERNAL       43031
#define IDM_MESSAGE_REPLYALL            43032
#define IDM_MESSAGE_REPLYALLEXTERNAL    43033
#define IDM_MESSAGE_SEARCH              43034
#define IDM_MESSAGE_UNMARK              43035
#define IDM_MESSAGE_UNMARKDELETED       43036
#define IDM_MESSAGE_UNMARKDOWNLOAD      43037
#define IDM_MESSAGE_UNMARKDOWNLOADTEXT  43038
#define IDM_MESSAGE_UNMARKSEEN          43039
#define IDM_MESSAGE_APPLYTEMPLATE       43100
#define IDM_MESSAGE_APPLYTEMPLATEEXTERNAL 43200
#define IDM_MESSAGE_ATTACHMENT          43300
#define IDM_MESSAGE_MOVE                43400
#define IDM_MESSAGE_OPENRECENT          43500
#define IDM_TOOL_ACCOUNT                44001
#define IDM_TOOL_ADDRESSBOOK            44002
#define IDM_TOOL_ATTACHMENT             44003
#define IDM_TOOL_CANCEL                 44004
#define IDM_TOOL_CHECKNEWMAIL           44005
#define IDM_TOOL_DIALUP                 44006
#define IDM_TOOL_HEADEREDIT             44007
#define IDM_TOOL_INSERTSIGNATURE        44008
#define IDM_TOOL_INSERTTEXTNONE         44009
#define IDM_TOOL_OPTIONS                44010
#define IDM_TOOL_PGPENCRYPT             44011
#define IDM_TOOL_PGPMIME                44012
#define IDM_TOOL_PGPSIGN                44013
#define IDM_TOOL_RECEIVE                44014
#define IDM_TOOL_REFORM                 44015
#define IDM_TOOL_REFORMALL              44016
#define IDM_TOOL_REFORMAUTO             44017
#define IDM_TOOL_SCRIPTNONE             44018
#define IDM_TOOL_SEND                   44019
#define IDM_TOOL_SMIMEENCRYPT           44020
#define IDM_TOOL_SMIMESIGN              44021
#define IDM_TOOL_SYNC                   44022
#define IDM_TOOL_GOROUND                44100
#define IDM_TOOL_SCRIPT                 44200
#define IDM_TOOL_SUBACCOUNT             44300
#define IDM_TOOL_INSERTTEXT             44400
#define IDM_VIEW_DROPDOWN               45001
#define IDM_VIEW_ENCODINGAUTODETECT     45002
#define IDM_VIEW_FILTERCUSTOM           45003
#define IDM_VIEW_FILTERNONE             45004
#define IDM_VIEW_FOCUSNEXT              45005
#define IDM_VIEW_FOCUSPREV              45006
#define IDM_VIEW_HTMLMODE               45007
#define IDM_VIEW_HTMLONLINEMODE         45008
#define IDM_VIEW_LOCKPREVIEW            45009
#define IDM_VIEW_NEXTACCOUNT            45010
#define IDM_VIEW_NEXTFOLDER             45011
#define IDM_VIEW_NEXTMESSAGE            45012
#define IDM_VIEW_NEXTMESSAGEPAGE        45013
#define IDM_VIEW_NEXTUNSEENMESSAGE      45014
#define IDM_VIEW_OPENLINK               45015
#define IDM_VIEW_PGPMODE                45016
#define IDM_VIEW_PREVACCOUNT            45017
#define IDM_VIEW_PREVFOLDER             45018
#define IDM_VIEW_PREVMESSAGE            45019
#define IDM_VIEW_PREVMESSAGEPAGE        45020
#define IDM_VIEW_QUOTEMODE              45021
#define IDM_VIEW_RAWMODE                45022
#define IDM_VIEW_REFRESH                45023
#define IDM_VIEW_SCROLLBOTTOM           45024
#define IDM_VIEW_SCROLLLINEDOWN         45025
#define IDM_VIEW_SCROLLLINEUP           45026
#define IDM_VIEW_SCROLLPAGEDOWN         45027
#define IDM_VIEW_SCROLLPAGEUP           45028
#define IDM_VIEW_SCROLLTOP              45029
#define IDM_VIEW_SELECTMESSAGE          45030
#define IDM_VIEW_SELECTMODE             45031
#define IDM_VIEW_SHOWFOLDER             45032
#define IDM_VIEW_SHOWHEADER             45033
#define IDM_VIEW_SHOWHEADERCOLUMN       45034
#define IDM_VIEW_SHOWPREVIEW            45035
#define IDM_VIEW_SHOWSTATUSBAR          45036
#define IDM_VIEW_SHOWSYNCDIALOG         45037
#define IDM_VIEW_SHOWTOOLBAR            45038
#define IDM_VIEW_SMIMEMODE              45039
#define IDM_VIEW_SORTASCENDING          45040
#define IDM_VIEW_SORTDESCENDING         45041
#define IDM_VIEW_SORTTHREAD             45042
#define IDM_VIEW_TEMPLATENONE           45043
#define IDM_VIEW_ENCODING               45100
#define IDM_VIEW_FILTER                 45200
#define IDM_VIEW_SORT                   45300
#define IDM_VIEW_TEMPLATE               45400
#define IDM_FOCUS_HEADEREDITITEM        46000
#define IDM_ADDRESSBOOK_ALLCATEGORY     47001
#define IDM_ADDRESSBOOK_CHANGEBCC       47002
#define IDM_ADDRESSBOOK_CHANGECC        47003
#define IDM_ADDRESSBOOK_CHANGETO        47004
#define IDM_ADDRESSBOOK_REMOVE          47005
#define IDM_ADDRESSBOOK_CATEGORY        47100
#define IDM_ATTACHMENT_OPEN             48001
#define IDM_ATTACHMENT_SAVE             48002
#define IDM_ATTACHMENT_SAVEALL          48003
#define IDM_ATTACHMENTEDIT_ADD          49001
#define IDM_ATTACHMENTEDIT_DELETE       49002
#define IDM_CONFIG_COLORS               50001
#define IDM_CONFIG_GOROUND              50002
#define IDM_CONFIG_RULES                50003
#define IDM_CONFIG_SIGNATURES           50004
#define IDM_CONFIG_TEXTS                50005
#define IDM_CONFIG_VIEWS                50006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        181
#define _APS_NEXT_COMMAND_VALUE         49000
#define _APS_NEXT_CONTROL_VALUE         1264
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
