//{{NO_DEPENDENCIES}}
// Microsoft eMbedded Visual C++ generated include file.
// Used by qmppc.rc
//
#define IDD_SYNC                        110
#define IDD_SELECTSYNCFILTER            111
#define IDD_CREATEFOLDER                112
#define IDD_PROGRESS                    113
#define IDD_DETACH                      114
#define IDD_SELECTADDRESS               115
#define IDD_ATTACHMENT                  117
#define IDD_MESSAGEPROPERTY             119
#define IDD_EXPORT                      120
#define IDD_IMPORT                      121
#define IDD_ACCOUNT                     132
#define IDD_ACCOUNTGENERAL              133
#define IDD_ACCOUNTUSER                 134
#define IDD_ACCOUNTDIALUP               135
#define IDD_ACCOUNTADVANCED             136
#define IDD_CREATEACCOUNT               139
#define IDD_MAILFOLDER                  140
#define IDD_FIND                        141
#define IDD_REPLACE                     142
#define IDD_CREATESUBACCOUNT            143
#define IDD_DIALUP                      144
#define IDD_SELECTDIALUPENTRY           145
#define IDD_FOLDERPROPERTY              146
#define IDD_SINGLEINPUTBOX              147
#define IDD_MULTIINPUTBOX               148
#define IDD_CUSTOMFILTER                150
#define IDD_MOVEMESSAGE                 151
#define IDD_RENAME                      152
#define IDD_MACROSEARCH                 153
#define IDD_FOLDERCONDITION             155
#define IDD_VIEWS                       157
#define IDD_VIEWSCOLUMN                 158
#define IDD_FOLDERPARAMETER             159
#define IDD_PARAMETER                   160
#define IDD_GOROUND                     161
#define IDD_GOROUNDCOURSE               162
#define IDD_GOROUNDENTRY                163
#define IDD_GOROUNDDIALUP               164
#define IDD_ACCOUNTDETAIL               165
#define IDD_RESOURCE                    166
#define IDD_SIGNATURES                  167
#define IDD_SIGNATURE                   168
#define IDD_FIXEDFORMTEXTS              170
#define IDD_FIXEDFORMTEXT               171
#define IDD_PASSWORD                    172
#define IDD_RULECOLORSETS               173
#define IDD_RULESCOLORS                 174
#define IDD_RULE                        175
#define IDD_COLOR                       176
#define IDD_COPYRULETEMPLATE            177
#define IDD_ARGUMENT                    178
#define IDD_CONDITIONS                  179
#define IDD_FILTERS                     180
#define IDD_FILTER                      181
#define IDD_SYNCFILTERSETS              182
#define IDD_SYNCFILTERS                 183
#define IDD_SYNCFILTER                  184
#define IDD_AUTOPILOT                   185
#define IDD_AUTOPILOTENTRY              186
#define IDD_CONFIRMSEND                 187
#define IDD_ADDRESSBOOKENTRY            188
#define IDD_ADDRESSBOOKADDRESS          189
#define IDD_ADDADDRESS                  190
#define IDD_TABTITLE                    191
#define IDD_OPTION                      197
#define IDD_OPTIONFOLDER                198
#define IDD_OPTIONLIST                  200
#define IDD_OPTIONADDRESSBOOK           201
#define IDD_OPTIONTAB                   202
#define IDD_OPTIONEDIT                  203
#define IDD_OPTIONPREVIEW               204
#define IDD_OPTIONMESSAGE               205
#define IDD_OPTIONHEADER                206
#define IDD_TEXTCOLOR                   207
#define IDD_OPTIONSECURITY              208
#define IDD_OPTIONMISC                  209
#define IDD_OPTIONEDIT2                 211
#define IDD_SECURITY                    212
#define IDD_OPTIONMISC2                 213
#define IDD_OPTIONCONFIRM               215
#define IDD_CONDITION                   217
#define IDD_CONDITIONARGUMENT           218
#define IDD_LISTSELECTBOX               219
#define IDD_COMBOSELECTBOX              220
#define IDD_LABEL                       221
#define IDD_CERTIFICATE                 222
#define IDD_OPTIONSEARCH                223
#define IDC_SYNCSTATUS                  1000
#define IDC_FILTERSETLIST               1001
#define IDC_SIZEGRIP                    1003
#define IDC_LOCALFOLDER                 1005
#define IDC_REMOTEFOLDER                1006
#define IDC_QUERYFOLDER                 1007
#define IDC_NAME                        1008
#define IDC_MACRO                       1009
#define IDC_MESSAGE                     1010
#define IDC_PROGRESS                    1011
#define IDC_ATTACHMENT                  1012
#define IDC_FOLDER                      1013
#define IDC_BROWSE                      1014
#define IDC_RENAME                      1015
#define IDC_LIST                        1016
#define IDC_ADDRESS                     1017
#define IDC_SELECTEDADDRESS             1018
#define IDC_TO                          1019
#define IDC_CC                          1020
#define IDC_BCC                         1021
#define IDC_REMOVE                      1022
#define IDC_CATEGORY                    1023
#define IDC_ADD                         1025
#define IDC_DATE                        1027
#define IDC_SUBJECT                     1028
#define IDC_ID                          1029
#define IDC_MESSAGESIZE                 1030
#define IDC_SEEN                        1031
#define IDC_REPLIED                     1032
#define IDC_FORWARDED                   1033
#define IDC_DELETED                     1034
#define IDC_SENT                        1035
#define IDC_DRAFT                       1036
#define IDC_MARKED                      1037
#define IDC_DOWNLOAD                    1038
#define IDC_DOWNLOADTEXT                1039
#define IDC_TOME                        1040
#define IDC_CCME                        1041
#define IDC_USER1                       1042
#define IDC_USER2                       1043
#define IDC_USER3                       1044
#define IDC_USER4                       1045
#define IDC_FROM                        1046
#define IDC_PATH                        1047
#define IDC_ENCODING                    1051
#define IDC_TEMPLATE                    1052
#define IDC_FILEPERMESSAGE              1053
#define IDC_EXPORTFLAGS                 1058
#define IDC_NORMAL                      1059
#define IDC_QMAIL20COMPATIBLE           1060
#define IDC_IGNORE                      1061
#define IDC_MULTIMESSAGES               1062
#define IDC_ACCOUNT                     1063
#define IDC_ADDACCOUNT                  1064
#define IDC_ADDSUBACCOUNT               1065
#define IDC_PROPERTY                    1068
#define IDC_RECEIVEHOST                 1069
#define IDC_SENDHOST                    1070
#define IDC_SENDAUTHENTICATE            1070
#define IDC_RECEIVEUSERNAME             1071
#define IDC_RECEIVEPASSWORD             1072
#define IDC_IDENTITY                    1072
#define IDC_SENDUSERNAME                1073
#define IDC_SENDPASSWORD                1074
#define IDC_TIMEOUT                     1074
#define IDC_CONNECTRECEIVEHOSTBEFORESEND 1075
#define IDC_INCOMINGPROTOCOL            1077
#define IDC_OUTGOINGPROTOCOL            1078
#define IDC_SINGLEFILE                  1079
#define IDC_MULTIPLEFILE                1080
#define IDC_BLOCKSIZE                   1081
#define IDC_INDEXBLOCKSIZE              1082
#define IDC_MAILFOLDER                  1083
#define IDC_ERROR                       1085
#define IDC_MATCHCASE                   1087
#define IDC_FINDNEXT                    1088
#define IDC_FINDPREV                    1089
#define IDC_FIND                        1090
#define IDC_REPLACE                     1091
#define IDC_REPLACENEXT                 1092
#define IDC_REPLACEPREV                 1093
#define IDC_REPLACEALL                  1094
#define IDC_NEVER                       1095
#define IDC_WHENEVERNOTCONNECTED        1096
#define IDC_CONNECT                     1097
#define IDC_ENTRY                       1098
#define IDC_SHOWDIALOG                  1099
#define IDC_DIALPROPERTY                1100
#define IDC_WAITBEFOREDISCONNECT        1101
#define IDC_SYNCFILTER                  1102
#define IDC_CANCEL                      1103
#define IDC_USERNAME                    1104
#define IDC_PASSWORD                    1105
#define IDC_DOMAIN                      1106
#define IDC_DIALFROM                    1107
#define IDC_TYPE                        1108
#define IDC_SYNCWHENOPEN                1109
#define IDC_CACHEWHENREAD               1110
#define IDC_INBOX                       1111
#define IDC_OUTBOX                      1112
#define IDC_SENTBOX                     1113
#define IDC_DRAFTBOX                    1114
#define IDC_TRASHBOX                    1115
#define IDC_VALUE                       1116
#define IDC_HIDE                        1117
#define IDC_VALUELIST                   1117
#define IDC_TREATASSENT                 1118
#define IDC_CLASS                       1119
#define IDC_COPY                        1122
#define IDC_ADDMESSAGEID                1123
#define IDC_SHOWHIDDEN                  1125
#define IDC_IGNOREUNSEEN                1126
#define IDC_CONDITION                   1127
#define IDC_CURRENT                     1128
#define IDC_RECURSIVE                   1129
#define IDC_ALLFOLDER                   1130
#define IDC_SEARCHBODY                  1131
#define IDC_DRIVER                      1133
#define IDC_FILTER                      1134
#define IDC_FILTERLABEL                 1135
#define IDC_REGEX                       1136
#define IDC_COLUMNS                     1138
#define IDC_EDIT                        1141
#define IDC_UP                          1142
#define IDC_DOWN                        1143
#define IDC_TITLE                       1144
#define IDC_INDENT                      1147
#define IDC_LINE                        1148
#define IDC_ASICON                      1150
#define IDC_LEFTALIGN                   1151
#define IDC_RIGHTALIGN                  1152
#define IDC_SORTTEXT                    1153
#define IDC_SORTNUMBER                  1154
#define IDC_SORTDATE                    1155
#define IDC_WIDTH                       1156
#define IDC_ASDEFAULT                   1157
#define IDC_APPLYDEFAULT                1158
#define IDC_INHERIT                     1159
#define IDC_APPLYTOALL                  1160
#define IDC_APPLYTOCHILDREN             1161
#define IDC_PARAMETER                   1163
#define IDC_SYNCABLE                    1166
#define IDC_COURSE                      1167
#define IDC_CONFIRM                     1172
#define IDC_SEQUENTIAL                  1173
#define IDC_PARALLEL                    1174
#define IDC_DIALUP                      1184
#define IDC_SUBACCOUNT                  1186
#define IDC_SENDRECEIVE                 1187
#define IDC_RECEIVE                     1188
#define IDC_SEND                        1189
#define IDC_SELECTFOLDER                1191
#define IDC_CONNECTRECEIVEBEFORESEND    1193
#define IDC_RECEIVEPORT                 1201
#define IDC_SENDPORT                    1202
#define IDC_RECEIVENOSECURE             1204
#define IDC_RECEIVESSL                  1205
#define IDC_RECEIVESTARTTLS             1206
#define IDC_SENDNOSECURE                1207
#define IDC_SENDSSL                     1208
#define IDC_SENDSTARTTLS                1209
#define IDC_RECEIVELOG                  1210
#define IDC_SENDLOG                     1211
#define IDC_RESOURCE                    1212
#define IDC_BACKUP                      1213
#define IDC_CHECKALL                    1214
#define IDC_CLEARALL                    1215
#define IDC_SIGNATURES                  1216
#define IDC_DEFAULT                     1217
#define IDC_SIGNATURE                   1218
#define IDC_TEXTS                       1219
#define IDC_TEXT                        1220
#define IDC_DONTSAVE                    1221
#define IDC_SESSION                     1222
#define IDC_SAVE                        1223
#define IDC_HINT                        1224
#define IDC_CACHE                       1225
#define IDC_RULECOLORSETS               1226
#define IDC_RULESCOLORS                 1232
#define IDC_MOVE                        1241
#define IDC_DELETE                      1245
#define IDC_APPLY                       1246
#define IDC_DIRECT                      1247
#define IDC_ACTION                      1250
#define IDC_ACCOUNTLABEL                1251
#define IDC_FOLDERLABEL                 1252
#define IDC_MACROLABEL                  1253
#define IDC_COLOR                       1254
#define IDC_CHOOSE                      1255
#define IDC_ARGUMENT                    1263
#define IDC_FILTERS                     1264
#define IDC_FILTERSETS                  1270
#define IDC_MAXLINE                     1272
#define IDC_MAXLINELABEL                1274
#define IDC_TYPELABEL                   1275
#define IDC_ENTRIES                     1276
#define IDC_INTERVAL                    1278
#define IDC_DISCARD                     1281
#define IDC_QUESTION                    1283
#define IDC_SORTKEY                     1285
#define IDC_ADDRESSES                   1286
#define IDC_RFC2822                     1291
#define IDC_ALIAS                       1292
#define IDC_CERTIFICATE                 1294
#define IDC_NEWENTRY                    1295
#define IDC_NEWADDRESS                  1296
#define IDC_COMMENT                     1298
#define IDC_JUNKBOX                     1306
#define IDC_SELECTOR                    1308
#define IDC_ACCOUNTSHOWALL              1309
#define IDC_ACCOUNTSHOWUNSEEN           1310
#define IDC_FOLDERSHOWALL               1311
#define IDC_FOLDERSHOWUNSEEN            1312
#define IDC_FONT                        1314
#define IDC_SHOWALL                     1315
#define IDC_HEADERFONT                  1315
#define IDC_SHOWUNSEEN                  1316
#define IDC_SINGLECLICK                 1317
#define IDC_COMBOBOXFONT                1317
#define IDC_POCKETOUTLOOK               1319
#define IDC_ADDRESSONLY                 1321
#define IDC_MULTILINE                   1322
#define IDC_REUSEOPEN                   1323
#define IDC_REUSECHANGE                 1324
#define IDC_SOUNDLABEL                  1325
#define IDC_SOUND                       1326
#define IDC_ONLYWHENCONNECTED           1327
#define IDC_WRAPWINDOWWIDTH             1329
#define IDC_WRAPCOLUMN                  1330
#define IDC_CHARINLINE                  1331
#define IDC_WORDWRAP                    1332
#define IDC_TABWIDTH                    1333
#define IDC_SHOWRULER                   1334
#define IDC_SHOWVERTICALSCROLLBAR       1337
#define IDC_SHOWHORIZONTALSCROLLBAR     1338
#define IDC_COLORS                      1339
#define IDC_SEENWAIT                    1340
#define IDC_SHOWTAB                     1341
#define IDC_SHOWNEWLINE                 1342
#define IDC_QUOTE1                      1345
#define IDC_QUOTE2                      1346
#define IDC_LINK                        1347
#define IDC_SYSTEMCOLOR                 1348
#define IDC_CUSTOMCOLOR                 1349
#define IDC_CHOOSEFOREGROUND            1350
#define IDC_CHOOSEBACKGROUND            1351
#define IDC_CHOOSEQUOTE1                1352
#define IDC_CHOOSEQUOTE2                1353
#define IDC_CHOOSELINK                  1354
#define IDC_WINDOWFONT                  1355
#define IDC_SYSTEMSTORE                 1356
#define IDC_CONFIRMDELETEMESSAGE        1361
#define IDC_CONFIRMEMPTYFOLDER          1362
#define IDC_CONFIRMEMPTYTRASH           1363
#define IDC_EMPTYTRASHONEXIT            1364
#define IDC_LOG                         1365
#define IDC_SAVEONDEACTIVATE            1367
#define IDC_WARNEXTENSION               1368
#define IDC_TEMPORARYFOLDER             1369
#define IDC_SAVEMESSAGEVIEWMODEPERFOLDER 1372
#define IDC_HIDEHEADERIFNOFOCUS         1379
#define IDC_COLUMN                      1380
#define IDC_AUTOREFORM                  1381
#define IDC_SMIMEENCRYPT                1383
#define IDC_SMIMESIGN                   1384
#define IDC_SMIMEMULTIPARTSIGNED        1385
#define IDC_SMIMEENCRYPTFORSELF         1386
#define IDC_PGPENCRYPT                  1387
#define IDC_PGPSIGN                     1388
#define IDC_PGPMIME                     1389
#define IDC_USEEXTERNALEDITOR           1390
#define IDC_EDITOR                      1391
#define IDC_AUTOCREATE                  1393
#define IDC_SECURITY                    1394
#define IDC_NOBCCFORML                  1396
#define IDC_FORWARDRFC822               1397
#define IDC_OPENADDRESSBOOK             1398
#define IDC_QUOTE                       1399
#define IDC_INCREMENTALSEARCH           1400
#define IDC_SHOWNEXTUNSEENWHENSCROLLEND 1403
#define IDC_AUTOAPPLYRULES              1404
#define IDC_MANUAL                      1405
#define IDC_AUTO                        1406
#define IDC_ADDTORECENTS                1408
#define IDC_CONDITIONS                  1411
#define IDC_AND                         1414
#define IDC_OR                          1415
#define IDC_CUSTOM                      1416
#define IDC_ARGUMENTS                   1418
#define IDC_FIELD                       1420
#define IDC_NUMBER                      1422
#define IDC_DESCRIPTION                 1423
#define IDC_OPENFOLDER                  1424
#define IDC_DEFAULTENCODING             1428
#define IDC_USE8BIT                     1429
#define IDC_LABELLABEL                  1430
#define IDC_LABEL                       1431
#define IDC_LABELTYPELABEL              1432
#define IDC_LABELTYPE                   1433
#define IDC_CONTINUE                    1436
#define IDC_LABELQUOTE1                 1438
#define IDC_LABELQUOTE2                 1439
#define IDC_LABELLINK                   1440
#define IDC_VIEWPLACEMENT               1445
#define IDC_SEARCHHEADER                1446

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        224
#define _APS_NEXT_COMMAND_VALUE         49000
#define _APS_NEXT_CONTROL_VALUE         1448
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
