//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by qmppc.rc
//
#define IDI_MAINFRAME                   102
#define IDB_TOOLBAR                     103
#define IDB_FOLDER                      104
#define IDB_HEADER                      105
#define IDB_LIST                        106
#define IDB_LISTDATA                    107
#define IDD_SYNC                        110
#define IDD_SELECTSYNCFILTER            111
#define IDD_CREATEFOLDER                112
#define IDD_PROGRESS                    113
#define IDD_DETACH                      114
#define IDD_ADDRESSBOOK                 115
#define IDD_INSERTTEXT                  116
#define IDD_ATTACHMENT                  117
#define IDB_ADDRESSBOOK                 118
#define IDD_MESSAGEPROPERTY             119
#define IDD_EXPORT                      120
#define IDD_IMPORT                      121
#define IDR_VIEWSORT                    123
#define IDR_MESSAGEMOVE                 124
#define IDR_VIEWFILTER                  125
#define IDR_VIEWTEMPLATE                126
#define IDR_VIEWENCODING                127
#define IDR_MESSAGEAPPLYTEMPLATE        128
#define IDR_MESSAGEAPPLYTEMPLATEEXTERNAL 129
#define IDR_MESSAGEATTACHMENT           130
#define IDR_TOOLSUBACCOUNT              131
#define IDD_ACCOUNT                     132
#define IDD_ACCOUNTGENERAL              133
#define IDD_ACCOUNTUSER                 134
#define IDD_ACCOUNTDIALUP               135
#define IDD_ACCOUNTADVANCED             136
#define IDR_TOOLGOROUND                 137
#define IDR_TOOLSCRIPT                  138
#define IDD_CREATEACCOUNT               139
#define IDD_MAILFOLDER                  140
#define IDD_FIND                        141
#define IDD_REPLACE                     142
#define IDD_CREATESUBACCOUNT            143
#define IDD_DIALUP                      144
#define IDD_SELECTDIALUPENTRY           145
#define IDD_FOLDERPROPERTY              146
#define IDD_SINGLEINPUTBOX              147
#define IDD_MULTIINPUTBOX               148
#define IDB_SYNCNOTIFICATION            149
#define IDC_SYNCSTATUS                  1000
#define IDS_SHOWTOOLBAR                 1001
#define IDC_FILTERSETLIST               1001
#define IDS_HIDETOOLBAR                 1002
#define IDS_SHOWSTATUSBAR               1003
#define IDC_SIZEGRIP                    1003
#define IDS_HIDESTATUSBAR               1004
#define IDS_SHOWFOLDER                  1005
#define IDC_LOCALFOLDER                 1005
#define IDS_HIDEFOLDER                  1006
#define IDC_REMOTEFOLDER                1006
#define IDS_SHOWHEADERCOLUMN            1007
#define IDC_QUERYFOLDER                 1007
#define IDS_HIDEHEADERCOLUMN            1008
#define IDC_NAME                        1008
#define IDS_SHOWPREVIEW                 1009
#define IDC_MACRO                       1009
#define IDS_HIDEPREVIEW                 1010
#define IDC_MESSAGE                     1010
#define IDS_SHOWHEADER                  1011
#define IDC_PROGRESS                    1011
#define IDS_HIDEHEADER                  1012
#define IDC_ATTACHMENT                  1012
#define IDS_THISFOLDER                  1013
#define IDC_FOLDER                      1013
#define IDS_NONE                        1014
#define IDC_BROWSE                      1014
#define IDS_GOROUND                     1015
#define IDC_RENAME                      1015
#define IDS_CANCEL                      1016
#define IDC_LIST                        1016
#define IDS_APPLYMESSAGERULES           1017
#define IDC_ADDRESS                     1017
#define IDS_CONFIRMOVERWRITE            1018
#define IDC_SELECTEDADDRESS             1018
#define IDS_CONFIRMEXECUTEATTACHMENT    1019
#define IDC_TO                          1019
#define IDS_CONFIRMDELETETEMPFILE       1020
#define IDC_CC                          1020
#define IDC_BCC                         1021
#define IDS_PROPERTY                    1021
#define IDC_REMOVE                      1022
#define IDS_ALLCATEGORY                 1022
#define IDC_CATEGORY                    1023
#define IDS_CATEGORY                    1023
#define IDS_CATEGORYALL                 1024
#define IDC_ADD                         1025
#define IDS_DEFAULTSUBACCOUNT           1025
#define IDS_ACCOUNT                     1026
#define IDC_DATE                        1027
#define IDS_TEMPLATENONE                1027
#define IDC_SUBJECT                     1028
#define IDS_SCRIPTNONE                  1028
#define IDC_ID                          1029
#define IDS_FOLDERLISTNAME              1029
#define IDC_MESSAGESIZE                 1030
#define IDS_FOLDERLISTID                1030
#define IDC_SEEN                        1031
#define IDS_FOLDERLISTCOUNT             1031
#define IDC_REPLIED                     1032
#define IDS_FOLDERLISTUNSEENCOUNT       1032
#define IDC_FORWARDED                   1033
#define IDS_FOLDERLISTINDEXSIZE         1033
#define IDC_DELETED                     1034
#define IDS_FOLDERLISTBOXSIZE           1034
#define IDC_SENT                        1035
#define IDS_FINDNOTFOUND                1035
#define IDC_DRAFT                       1036
#define IDS_CONFIRMCLOSEEDITFRAME       1036
#define IDC_MARKED                      1037
#define IDS_DIALUPCONNECT               1037
#define IDC_DOWNLOAD                    1038
#define IDS_DIALUPDISCONNECT            1038
#define IDC_DOWNLOADTEXT                1039
#define IDS_NORMALFOLDER                1039
#define IDC_TOME                        1040
#define IDS_QUERYFOLDER                 1040
#define IDC_CCME                        1041
#define IDS_LOCALFOLDER                 1041
#define IDC_USER1                       1042
#define IDS_REMOTEFOLDER                1042
#define IDC_USER2                       1043
#define IDS_FOLDERTYPETEMPLATE          1043
#define IDC_USER3                       1044
#define IDC_USER4                       1045
#define IDC_FROM                        1046
#define IDC_PATH                        1047
#define IDC_ENCODING                    1051
#define IDC_TEMPLATE                    1052
#define IDC_FILEPERMESSAGE              1053
#define IDC_EXPORTFLAGS                 1058
#define IDC_NORMAL                      1059
#define IDC_QMAIL20COMPATIBLE           1060
#define IDC_IGNORE                      1061
#define IDC_MULTIMESSAGES               1062
#define IDC_ACCOUNT                     1063
#define IDC_ADDACCOUNT                  1064
#define IDC_ADDSUBACCOUNT               1065
#define IDC_PROPERTY                    1068
#define IDC_RECEIVEHOST                 1069
#define IDC_SENDHOST                    1070
#define IDC_SENDAUTHENTICATE            1070
#define IDC_RECEIVEUSERNAME             1071
#define IDC_RECEIVEPASSWORD             1072
#define IDC_IDENTITY                    1072
#define IDC_SENDUSERNAME                1073
#define IDC_MYADDRESS                   1073
#define IDC_SENDPASSWORD                1074
#define IDC_TIMEOUT                     1074
#define IDC_CONNECTRECEIVEHOSTBEFORESEND 1075
#define IDC_INCOMINGPROTOCOL            1077
#define IDC_OUTGOINGPROTOCOL            1078
#define IDC_SINGLEFILE                  1079
#define IDC_MULTIPLEFILE                1080
#define IDC_BLOCKSIZE                   1081
#define IDC_CACHEBLOCKSIZE              1082
#define IDC_MAILFOLDER                  1083
#define IDC_ERROR                       1085
#define IDC_MATCHCASE                   1087
#define IDC_FINDNEXT                    1088
#define IDC_FINDPREV                    1089
#define IDC_FIND                        1090
#define IDC_REPLACE                     1091
#define IDC_REPLACENEXT                 1092
#define IDC_REPLACEPREV                 1093
#define IDC_REPLACEALL                  1094
#define IDC_NEVER                       1095
#define IDC_WHENEVERNOTCONNECTED        1096
#define IDC_CONNECT                     1097
#define IDC_ENTRY                       1098
#define IDC_SHOWDIALOG                  1099
#define IDS_FILTER_EXPORT               1100
#define IDC_DIALPROPERTY                1100
#define IDS_FILTER_IMPORT               1101
#define IDC_WAITBEFOREDISCONNECT        1101
#define IDS_FILTER_INSERT               1102
#define IDC_SYNCFILTER                  1102
#define IDC_CANCEL                      1103
#define IDS_FILTER_OPEN                 1103
#define IDS_FILTER_SAVE                 1104
#define IDC_USERNAME                    1104
#define IDS_FILTER_ATTACHMENT           1105
#define IDC_PASSWORD                    1105
#define IDC_DOMAIN                      1106
#define IDC_DIALFROM                    1107
#define IDC_TYPE                        1108
#define IDC_SYNCWHENOPEN                1109
#define IDC_CACHEWHENREAD               1110
#define IDC_INBOX                       1111
#define IDC_OUTBOX                      1112
#define IDC_SENTBOX                     1113
#define IDC_DRAFTBOX                    1114
#define IDC_TRASHBOX                    1115
#define IDC_VALUE                       1116
#define IDC_HIDE                        1117
#define IDS_SYNCMSG_FINISHED            2001
#define IDS_SYNCMSG_SENDMESSAGES        2002
#define IDS_APPLYRULE_CHECKINGMESSAGES  2101
#define IDS_APPLYRULE_APPLYINGRULE      2102
#define IDS_ADDRESSBOOK_NAME            2201
#define IDS_ADDRESSBOOK_ADDRESS         2202
#define IDS_ADDRESSBOOK_COMMENT         2203
#define IDS_ERROR_CREATEFOLDER          10000
#define IDS_ERROR_EXECUTEATTACHMENT     10001
#define IDS_ERROR_DIALUP                10002
#define IDM_EDIT_CLEARDELETED           40001
#define IDM_EDIT_COPY                   40002
#define IDM_EDIT_CUT                    40003
#define IDM_EDIT_DELETE                 40004
#define IDM_EDIT_DELETECACHE            40005
#define IDM_EDIT_DELETEDIRECT           40006
#define IDM_EDIT_FIND                   40007
#define IDM_EDIT_FINDNEXT               40008
#define IDM_EDIT_FINDPREV               40009
#define IDM_EDIT_MOVECHARLEFT           40010
#define IDM_EDIT_MOVECHARRIGHT          40011
#define IDM_EDIT_MOVELINEDOWN           40012
#define IDM_EDIT_MOVELINEEND            40013
#define IDM_EDIT_MOVELINESTART          40014
#define IDM_EDIT_MOVELINEUP             40015
#define IDM_EDIT_MOVEPAGEDOWN           40016
#define IDM_EDIT_MOVEPAGEUP             40017
#define IDM_EDIT_MOVEDOCEND             40018
#define IDM_EDIT_MOVEDOCSTART           40019
#define IDM_EDIT_PASTE                  40020
#define IDM_EDIT_PASTEWITHQUOTE         40021
#define IDM_EDIT_REDO                   40022
#define IDM_EDIT_REPLACE                40023
#define IDM_EDIT_SELECTALL              40024
#define IDM_EDIT_UNDO                   40025
#define IDM_FILE_CLOSE                  41001
#define IDM_FILE_DRAFT                  41002
#define IDM_FILE_EMPTYTRASH             41003
#define IDM_FILE_EXIT                   41004
#define IDM_FILE_EXPORT                 41005
#define IDM_FILE_IMPORT                 41006
#define IDM_FILE_INSERT                 41007
#define IDM_FILE_OFFLINE                41008
#define IDM_FILE_OPEN                   41009
#define IDM_FILE_PRINT                  41010
#define IDM_FILE_SAVE                   41011
#define IDM_FILE_SEND                   41012
#define IDM_FILE_SENDNOW                41013
#define IDM_FOLDER_COMPACT              42001
#define IDM_FOLDER_CREATE               42002
#define IDM_FOLDER_DELETE               42003
#define IDM_FOLDER_EMPTY                42004
#define IDM_FOLDER_PROPERTY             42005
#define IDM_FOLDER_UPDATE               42006
#define IDM_MESSAGE_APPLYRULE           43001
#define IDM_MESSAGE_APPLYTEMPLATENONE   43002
#define IDM_MESSAGE_APPLYTEMPLATENONEEXTERNAL 43003
#define IDM_MESSAGE_COMBINE             43004
#define IDM_MESSAGE_CREATEFROMCLIPBOARD 43005
#define IDM_MESSAGE_DELETEATTACHMENT    43006
#define IDM_MESSAGE_DETACH              43007
#define IDM_MESSAGE_DRAFTFROMCLIPBOARD  43008
#define IDM_MESSAGE_EDIT                43009
#define IDM_MESSAGE_EDITEXTERNAL        43010
#define IDM_MESSAGE_EXPANDDIGEST        43011
#define IDM_MESSAGE_FORWARD             43012
#define IDM_MESSAGE_FORWARDEXTERNAL     43013
#define IDM_MESSAGE_MARK                43014
#define IDM_MESSAGE_MARKDOWNLOAD        43015
#define IDM_MESSAGE_MARKSEEN            43016
#define IDM_MESSAGE_MARKUNSEEN          43017
#define IDM_MESSAGE_MOVEOTHER           43018
#define IDM_MESSAGE_NEW                 43019
#define IDM_MESSAGE_NEWEXTERNAL         43020
#define IDM_MESSAGE_PROPERTY            43021
#define IDM_MESSAGE_REPLY               43022
#define IDM_MESSAGE_REPLYEXTERNAL       43023
#define IDM_MESSAGE_REPLYALL            43024
#define IDM_MESSAGE_REPLYALLEXTERNAL    43025
#define IDM_MESSAGE_SEARCH              43026
#define IDM_MESSAGE_UNMARK              43027
#define IDM_MESSAGE_APPLYTEMPLATE       43100
#define IDM_MESSAGE_APPLYTEMPLATEEXTERNAL 43200
#define IDM_MESSAGE_ATTACHMENT          43300
#define IDM_MESSAGE_MOVE                43400
#define IDM_TOOL_ACCOUNT                44001
#define IDM_TOOL_ADDRESSBOOK            44002
#define IDM_TOOL_ATTACHMENT             44003
#define IDM_TOOL_CANCEL                 44004
#define IDM_TOOL_DIALUP                 44005
#define IDM_TOOL_ENCRYPT                44006
#define IDM_TOOL_HEADEREDIT             44007
#define IDM_TOOL_INSERTSIGNATURE        44008
#define IDM_TOOL_INSERTTEXT             44009
#define IDM_TOOL_OPTIONS                44010
#define IDM_TOOL_RECEIVE                44011
#define IDM_TOOL_REFORM                 44012
#define IDM_TOOL_REFORMALL              44013
#define IDM_TOOL_REFORMAUTO             44014
#define IDM_TOOL_SCRIPTNONE             44015
#define IDM_TOOL_SEND                   44016
#define IDM_TOOL_SIGN                   44017
#define IDM_TOOL_SYNC                   44018
#define IDM_TOOL_GOROUND                44100
#define IDM_TOOL_SCRIPT                 44200
#define IDM_TOOL_SUBACCOUNT             44300
#define IDM_VIEW_DECRYPTVERIFYMODE      45001
#define IDM_VIEW_ENCODINGAUTODETECT     45002
#define IDM_VIEW_FILTERCUSTOM           45003
#define IDM_VIEW_FILTERNONE             45004
#define IDM_VIEW_FOCUSNEXT              45005
#define IDM_VIEW_FOCUSPREV              45006
#define IDM_VIEW_HTMLMODE               45007
#define IDM_VIEW_LOCKPREVIEW            45008
#define IDM_VIEW_NEXTACCOUNT            45009
#define IDM_VIEW_NEXTFOLDER             45010
#define IDM_VIEW_NEXTMESSAGE            45011
#define IDM_VIEW_NEXTMESSAGEPAGE        45012
#define IDM_VIEW_NEXTUNSEENMESSAGE      45013
#define IDM_VIEW_OPENLINK               45014
#define IDM_VIEW_PREVACCOUNT            45015
#define IDM_VIEW_PREVFOLDER             45016
#define IDM_VIEW_PREVMESSAGE            45017
#define IDM_VIEW_PREVMESSAGEPAGE        45018
#define IDM_VIEW_RAWMODE                45019
#define IDM_VIEW_REFRESH                45020
#define IDM_VIEW_SCROLLBOTTOM           45021
#define IDM_VIEW_SCROLLLINEDOWN         45022
#define IDM_VIEW_SCROLLLINEUP           45023
#define IDM_VIEW_SCROLLPAGEDOWN         45024
#define IDM_VIEW_SCROLLPAGEUP           45025
#define IDM_VIEW_SCROLLTOP              45026
#define IDM_VIEW_SELECTMESSAGE          45027
#define IDM_VIEW_SELECTMODE             45028
#define IDM_VIEW_SHOWFOLDER             45029
#define IDM_VIEW_SHOWHEADER             45030
#define IDM_VIEW_SHOWHEADERCOLUMN       45031
#define IDM_VIEW_SHOWPREVIEW            45032
#define IDM_VIEW_SHOWSTATUSBAR          45033
#define IDM_VIEW_SHOWSYNCDIALOG         45034
#define IDM_VIEW_SHOWTOOLBAR            45035
#define IDM_VIEW_SORTASCENDING          45036
#define IDM_VIEW_SORTDESCENDING         45037
#define IDM_VIEW_SORTTHREAD             45038
#define IDM_VIEW_TEMPLATENONE           45039
#define IDM_VIEW_ENCODING               45100
#define IDM_VIEW_FILTER                 45200
#define IDM_VIEW_SORT                   45300
#define IDM_VIEW_TEMPLATE               45400
#define IDM_FOCUS_HEADEREDITITEM        46000
#define IDM_ADDRESSBOOK_ALLCATEGORY     47001
#define IDM_ADDRESSBOOK_CATEGORY        47100
#define IDM_ATTACHMENT_OPEN             48001
#define IDM_ATTACHMENT_SAVE             48002
#define IDM_ATTACHMENT_SAVEALL          48003

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        150
#define _APS_NEXT_COMMAND_VALUE         48000
#define _APS_NEXT_CONTROL_VALUE         1118
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
