//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by model.rc
//
#define IDS_CONDITION_SEEN_DESCRIPTION  20000
#define IDS_CONDITION_UNSEEN_DESCRIPTION 20001
#define IDS_CONDITION_MARKED_DESCRIPTION 20002
#define IDS_CONDITION_UNMARKED_DESCRIPTION 20003
#define IDS_CONDITION_DELETED_DESCRIPTION 20004
#define IDS_CONDITION_UNDELETED_DESCRIPTION 20005
#define IDS_CONDITION_MULTIPART_DESCRIPTION 20006
#define IDS_CONDITION_JUNK_DESCRIPTION  20007
#define IDS_CONDITION_TRUE_DESCRIPTION  20008
#define IDS_CONDITION_CONTAIN_DESCRIPTION 20009
#define IDS_CONDITION_CONTAIN_FIELD     20010
#define IDS_CONDITION_CONTAIN_VALUE     20011
#define IDS_CONDITION_BEGINWITH_DESCRIPTION 20012
#define IDS_CONDITION_BEGINWITH_FIELD   20013
#define IDS_CONDITION_BEGINWITH_VALUE   20014
#define IDS_CONDITION_EQUAL_DESCRIPTION 20015
#define IDS_CONDITION_EQUAL_FIELD       20016
#define IDS_CONDITION_EQUAL_VALUE       20017
#define IDS_CONDITION_MATCH_DESCRIPTION 20018
#define IDS_CONDITION_MATCH_FIELD       20019
#define IDS_CONDITION_MATCH_VALUE       20020
#define IDS_CONDITION_LARGER_DESCRIPTION 20021
#define IDS_CONDITION_LARGER_VALUE      20022
#define IDS_CONDITION_SMALLER_DESCRIPTION 20023
#define IDS_CONDITION_SMALLER_VALUE     20024
#define IDS_CONDITION_OLDER_DESCRIPTION 20025
#define IDS_CONDITION_OLDER_VALUE       20026
#define IDS_CONDITION_NEWER_DESCRIPTION 20027
#define IDS_CONDITION_NEWER_VALUE       20028
#define IDS_CONDITIONTYPE_AND           20050
#define IDS_CONDITIONTYPE_OR            20051
#define IDS_RULEACTION_NONE             20100
#define IDS_RULEACTION_MOVE             20101
#define IDS_RULEACTION_COPY             20102
#define IDS_RULEACTION_DELETE           20103
#define IDS_RULEACTION_LABEL            20104
#define IDS_RULEACTION_DELETEDIRECT     20105
#define IDS_RULEACTION_DELETECACHE      20106
#define IDS_RULEACTION_APPLYMACRO       20107
#define IDS_FOLDER_SEARCH               20200

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
