=begin
=QMAIL3のドキュメント

==目次
*はじめに
  *QMAIL3とは
  *特徴
  *動作環境
  *このドキュメントについて
*インストールとアンインストール
  *((<インストール|URL:Install.html>))
    *((<インストーラによるインストール|URL:InstallWithInstaller.html>))
    *((<Zipファイルによるインストール|URL:InstallWithZip.html>))
  *((<バージョンアップ|URL:VersionUp.html>))
  *((<アンインストール|URL:Uninstall.html>))
*チュートリアル
  *((<起動|URL:Launch.html>))
  *((<画面構成|URL:WindowsAndViews.html>))
    *メインウィンドウ
      *メニュー
      *ツールバー
      *ステータスバー
    *メッセージウィンドウ
      *メニュー
      *ツールバー
      *ステータスバー
    *エディットウィンドウ
      *メニュー
      *ツールバー
      *ステータスバー
    *アドレス帳ウィンドウ
      *メニュー
      *ツールバー
      *ステータスバー
  *POP3でメールを使う
    *((<アカウントの作成|URL:CreatePop3Account.html>))
    *((<メールを読む|URL:ReadPop3Message.html>))
    *((<メールを書く|URL:WritePop3Message.html>))
  *IMAP4でメールを使う
    *((<アカウントの作成|URL:CreateImap4Account.html>))
    *((<メールを読む|URL:ReadImap4Message.html>))
    *((<メールを書く|URL:WriteImap4Message.html>))
  *NetNewsを使う
    *((<アカウントの作成|URL:CreateNntpAccount.html>))
    *((<グループの購読|URL:SubscribeNntpGroup.html>))
    *((<ニュースを読む|URL:ReadNntpMessage.html>))
    *((<ニュースを投稿する|URL:PostNntpMessage.html>))
  *RSSを使う
    *((<アカウントの作成|URL:CreateRssAccount.html>))
    *((<フィードの購読|URL:SubscribeRssFeed.html>))
    *((<フィードを読む|URL:ReadRssFeed.html>))
  *振り分けルールを設定する
*機能
  *((<アカウント|URL:Account.html>))
    *((<サブアカウント|URL:SubAccount.html>))
    *((<マルチアカウント|URL:MultiAccount.html>))
  *((<フォルダ|URL:Folder.html>))
    *((<フォルダのプロパティ|URL:FolderProperty.html>))
      *((<一般|URL:FolderPropertyPage.html>))
      *((<検索条件|URL:FolderConditionPage.html>))
      *((<パラメータ|URL:FolderParameterPage.html>))
        *((<メールアカウントのパラメータ|URL:FolderPropertyMailParameter.html>))
        *((<RSSアカウントのパラメータ|URL:FolderPropertyRssParameter.html>))
  *((<オンラインとオフライン|URL:OnlineOffline.html>))
  *((<メッセージの移動とコピー|URL:MoveMessage.html>))
  *((<振り分け|URL:ApplyRules.html>))
  *プロトコル依存のトピック
    *POP3
      *部分受信とダウンロード予約
      *選択削除
  *((<巡回|URL:GoRound.html>))
  *((<自動巡回|URL:AutoPilot.html>))
  *((<新着メッセージ通知|URL:Recents.html>))
  *((<スレッド表示|URL:Thread.html>))
  *((<HTML表示|URL:HtmlView.html>))
  *((<フラグ|URL:Flag.html>))
  *((<ラベル|URL:Label.html>))
  *((<検索|URL:Search.html>))
    *((<基本検索|URL:MacroSearch.html>))
    *((<IMAP4検索|URL:Imap4Search.html>))
    *((<全文検索|URL:FullTextSearch.html>))
  *((<アドレス帳|URL:AddressBook.html>))
    *((<外部アドレス帳|URL:ExternalAddressBook.html>))
    *((<アドレスの自動補完|URL:AddressAutoComplete.html>))
  *((<添付ファイル|URL:Attachment.html>))
  *((<署名|URL:Signature.html>))
  *((<定型文|URL:FixedFormText.html>))
  *((<テンプレート|URL:Template.html>))
    *((<作成用のテンプレート|URL:CreateTemplate.html>))
    *((<表示用のテンプレート|URL:ViewTemplate.html>))
    *((<その他のテンプレート|URL:OtherTemplate.html>))
  *((<フィルタ|URL:Filter.html>))
  *((<同期フィルタ|URL:SyncFilter.html>))
  *((<リストビューの色|URL:Colors.html>))
  *((<リストビューのカスタマイズ|URL:CustomizeListView.html>))
  *((<整形|URL:Reform.html>))
  *((<メッセージ表示モード|URL:MessageViewMode.html>))
  *((<セキュリティモード|URL:SecurityMode.html>))
  *((<ダイアルアップ|URL:Dialup.html>))
  *((<SSL|URL:SSL.html>))
  *((<"S/MIME"|URL:SMIME.html>))
  *((<ルート証明書|URL:RootCertificate.html>))
  *((<PGPとGnuPG|URL:PGP.html>))
  *((<印刷|URL:Printing.html>))
  *((<インポートとエクスポート|URL:ImportAndExport.html>))
  *((<外部エディタ|URL:ExternalEditor.html>))
  *((<フォント|URL:Font.html>))
  *((<スパムフィルタ|URL:JunkFilter.html>))
  *((<スクリプト|URL:Script.html>))
  *((<ドラッグアンドドロップ|URL:DragAndDrop.html>))
  *((<保守|URL:Maintenance.html>))
  *((<コマンドライン|URL:CommandLine.html>))
  *((<ログ|URL:Log.html>))
  *((<正規表現|URL:RegularExpression.html>))
  *((<プロファイル|URL:Profile.html>))
  *((<メニューのカスタマイズ|URL:CustomizeMenus.html>))
  *((<ツールバーのカスタマイズ|URL:CustomizeToolbars.html>))
  *((<キーボードショートカットのカスタマイズ|URL:CustomizeAccelerators.html>))
*アカウントの設定
  *((<アカウントの管理|URL:ManageAccount.html>))
  *((<アカウントの作成|URL:CreateAccount.html>))
  *((<アカウントのプロパティ|URL:AccountProperty.html>))
*((<オプションの設定|URL:Options.html>))
*((<アクション|URL:Action.html>))
*((<マクロ|URL:Macro.html>))
  *((<型|URL:MacroType.html>))
  *((<変数|URL:MacroVariable.html>))
  *((<関数|URL:MacroFunction.html>))
*設定ファイル
  *プロファイル
    *addressbook.xml
    *autopilot.xml
    *colors.xml
    *filters.xml
    *fonts.xml
    *goround.xml
    *header.xml
    *headeredit.xml
    *keymap.xml
    *menus.xml
    *passwords.xml
    *((<qmail.xml|URL:QmailXml.html>))
    *resources.xml
    *rules.xml
    *signatures.xml
    *syncfilters.xml
    *tabs.xml
    *texts.xml
    *toolbars.xml
    *views.xml
  *アカウント
    *account.xml
    *folders.xml
    *views.xml
*((<FAQ|URL:FAQ.html>))

=end
