=begin
=関数

@から始まる文字列は関数呼び出しを表します。たとえば、

 @Seen()

は、((<@Seen|URL:SeenFunction.html>))という関数の呼び出しを表します。関数を呼び出すときに引数を渡すときには、()内に引数を指定します。例えば、ひとつの引数を渡すには、

 @MessageBox('Test')

のようにします。また、

 @Concat('String1', 'String2')

のように複数の引数を渡すこともできます。

定義されている関数は以下のリストを参照してください。((<@Defun|URL:DefunFunction.html>))を使用すると独自の関数を定義することもできます。


==関数のリスト
*((<@Account|URL:AccountFunction.html>))
*((<@AccountClass|URL:AccountClassFunction.html>))
*((<@AccountDirectory|URL:AccountDirectoryFunction.html>))
*((<@Add|URL:AddFunction.html>))
*((<@Address|URL:AddressFunction.html>))
*((<@AddressBook|URL:AddressBookFunction.html>))
*((<@And|URL:AndFunction.html>))
*((<@Attachment|URL:AttachmentFunction.html>))
*((<@BeginWith|URL:BeginWithFunction.html>))
*((<@Body|URL:BodyFunction.html>))
*((<@BodyCharset|URL:BodyCharsetFunction.html>))
*((<@Catch|URL:CatchFunction.html>))
*((<@Clipboard|URL:ClipboardFunction.html>))
*((<@ComputerName|URL:ComputerNameFunction.html>))
*((<@Concat|URL:ConcatFunction.html>))
*((<@Contain|URL:ContainFunction.html>))
*((<@Copy|URL:CopyFunction.html>))
*((<@Date|URL:DateFunction.html>))
*((<@Decode|URL:DecodeFunction.html>))
*((<@Defun|URL:DefunFunction.html>))
*((<@Delete|URL:DeleteFunction.html>))
*((<@DeleteAttachment|URL:DeleteAttachmentFunction.html>))
*((<@Deleted|URL:DeletedFunction.html>))
*((<@Download|URL:DownloadFunction.html>))
*((<@DownloadText|URL:DownloadTextFunction.html>))
*((<@Draft|URL:DraftFunction.html>))
*((<@Equal|URL:EqualFunction.html>))
*((<@Eval|URL:EvalFunction.html>))
*((<@Execute|URL:ExecuteFunction.html>))
*((<@Exist|URL:ExistFunction.html>))
*((<@Exit|URL:ExitFunction.html>))
*((<@False|URL:FalseFunction.html>))
*((<@Field|URL:FieldFunction.html>))
*((<@FieldParameter|URL:FieldParameterFunction.html>))
*((<@Find|URL:FindFunction.html>))
*((<@FindEach|URL:FindEachFunction.html>))
*((<@Flag|URL:FlagFunction.html>))
*((<@Folder|URL:FolderFunction.html>))
*((<@FolderFlag|URL:FolderFlagFunction.html>))
*((<@FolderParameter|URL:FolderParameterFunction.html>))
*((<@ForEach|URL:ForEachFunction.html>))
*((<@FormatAddress|URL:FormatAddressFunction.html>))
*((<@FormatDate|URL:FormatDateFunction.html>))
*((<@Forwarded|URL:ForwardedFunction.html>))
*((<@Greater|URL:GreaterFunction.html>))
*((<@Header|URL:HeaderFunction.html>))
*((<@HtmlEscape|URL:HtmlEscapeFunction.html>))
*((<@I|URL:IFunction.html>))
*((<@Id|URL:IdFunction.html>))
*((<@Identity|URL:IdentityFunction.html>))
*((<@If|URL:IfFunction.html>))
*((<@Include|URL:IncludeFunction.html>))
*((<@InputBox|URL:InputBoxFunction.html>))
*((<@InvokeAction|URL:InvokeActionFunction.html>))
*((<@Junk|URL:JunkFunction.html>))
*((<@Label|URL:LabelFunction.html>))
*((<@Length|URL:LengthFunction.html>))
*((<@Less|URL:LessFunction.html>))
*((<@Load|URL:LoadFunction.html>))
*((<@LookupAddressBook|URL:LookupAddressBookFunction.html>))
*((<@Marked|URL:MarkedFunction.html>))
*((<@MessageBox|URL:MessageBoxFunction.html>))
*((<@MessageCount|URL:MessageCountFunction.html>))
*((<@MessageId|URL:MessageIdFunction.html>))
*((<@Messages|URL:MessagesFunction.html>))
*((<@Move|URL:MoveFunction.html>))
*((<@Multipart|URL:MultipartFunction.html>))
*((<@Name|URL:NameFunction.html>))
*((<@New|URL:NewFunction.html>))
*((<@Not|URL:NotFunction.html>))
*((<@Or|URL:OrFunction.html>))
*((<@OSVersion|URL:OSVersionFunction.html>))
*((<@Param|URL:ParamFunction.html>))
*((<@ParseURL|URL:ParseURLFunction.html>))
*((<@Part|URL:PartFunction.html>))
*((<@Partial|URL:PartialFunction.html>))
*((<@Passed|URL:PassedFunction.html>))
*((<@ProcessId|URL:ProcessIdFunction.html>))
*((<@Profile|URL:ProfileFunction.html>))
*((<@ProfileName|URL:ProfileNameFunction.html>))
*((<@Progn|URL:PrognFunction.html>))
*((<@Quote|URL:QuoteFunction.html>))
*((<@References|URL:ReferencesFunction.html>))
*((<@RegexFind|URL:RegexFindFunction.html>))
*((<@RegexMatch|URL:RegexMatchFunction.html>))
*((<@RegexReplace|URL:RegexReplaceFunction.html>))
*((<@Remove|URL:RemoveFunction.html>))
*((<@Replied|URL:RepliedFunction.html>))
*((<@Save|URL:SaveFunction.html>))
*((<@SaveAttachment|URL:SaveAttachmentFunction.html>))
*((<@Script|URL:ScriptFunction.html>))
*((<@Seen|URL:SeenFunction.html>))
*((<@SelectBox|URL:SelectBoxFunction.html>))
*((<@Selected|URL:SelectedFunction.html>))
*((<@Sent|URL:SentFunction.html>))
*((<@Set|URL:SetFunction.html>))
*((<@Size|URL:SizeFunction.html>))
*((<@SpecialFolder|URL:SpecialFolderFunction.html>))
*((<@SubAccount|URL:SubAccountFunction.html>))
*((<@Subject|URL:SubjectFunction.html>))
*((<@Substring|URL:SubstringFunction.html>))
*((<@SubstringAfter|URL:SubstringAfterFunction.html>))
*((<@SubstringBefore|URL:SubstringBeforeFunction.html>))
*((<@Subtract|URL:SubtractFunction.html>))
*((<@Thread|URL:ThreadFunction.html>))
*((<@True|URL:TrueFunction.html>))
*((<@UnseenMessageCount|URL:UnseenMessageCountFunction.html>))
*((<@URI|URL:URIFunction.html>))
*((<@User1|URL:User1Function.html>))
*((<@User2|URL:User2Function.html>))
*((<@User3|URL:User3Function.html>))
*((<@User4|URL:User4Function.html>))
*((<@Variable|URL:VariableFunction.html>))
*((<@While|URL:WhileFunction.html>))


==呼び出し可能な関数
各関数は、状況に応じて呼び出し可能であるかどうかが決まっています。例えば、@AddressBookはUIが存在しない場合には呼び出せません。呼び出し可能であるかどうかを決定する条件には、以下のようなものがあります。

*UIが必要
*UIスレッドからのみ呼び出し可能
*メッセージに対する変更が可能

マクロを呼び出すことのできる各場面において、上記の条件は以下のように設定されます。

*((<作成用のテンプレート|URL:CreateTemplate.html>))
  *UIあり
  *UIスレッド
  *変更可能
*((<表示用のテンプレート|URL:ViewTemplate.html>))
  *UIあり
  *UIスレッド
  *変更不可
*((<エクスポート・印刷・引用符付き貼り付けのテンプレート|URL:OtherTemplate.html>))
  *UIあり
  *UIスレッド
  *変更不可
*((<MessageMacroアクション|URL:MessageMacroAction.html>))
  *UIあり
  *UIスレッド
  *変更可能
*((<X-QMAIL-Macro, X-QMAIL-DraftMacro|URL:SpecialHeaders.html>))
  *UIあり
  *UIスレッド
  *変更可能
*((<手動振り分け・アクティブ振り分け|URL:ApplyRules.html>))（手動でのメッセージ移動や手動振り分けから引き起こされた場合）の条件
  *UIあり
  *UIスレッド
  *変更不可
*((<自動振り分け・アクティブ振り分け|URL:ApplyRules.html>))（自動振り分けから引き起こされた場合）の条件
  *UIなし
  *バックグラウンドスレッド
  *変更不可
*((<フィルタ|URL:Filter.html>))
  *UIなし
  *UIスレッド
  *変更不可
*((<同期フィルタ|URL:SyncFilter.html>))
  *UIなし
  *バックグラウンドスレッド
  *変更不可
*((<基本検索|URL:MacroSearch.html>))のマクロ
  *UIあり
  *UIスレッド
  *変更不可
*((<ヘッダビュー|URL:CustomizeHeaderView.html>))
  *UIあり
  *UIスレッド
  *変更不可
*((<リストビューの色|URL:Colors.html>))
  *UIなし
  *UIスレッド
  *変更不可
*((<ヘッダカラム|URL:CustomizeListView.html>))
  *UIなし
  *UIスレッド
  *変更不可
*((<動的メニュー|URL:CustomizeMenus.html>))
  *UIなし
  *UIスレッド
  *変更不可
*((<フォント|URL:Font.html>))
  *UIあり
  *UIスレッド
  *変更不可

各関数がどの条件で呼び出し可能かは各関数の説明を参照してください。

=end
